import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Form from '@/components/form'
import Footer from '@/components/footer'
import Button from '@/components/Button'

export default function Home() {
  return (
    <>
      <Head>
        <title>Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/igfavicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <Image src={'/images/ig-phones.png'} alt="instagram phone" width={380} height={600} className={styles.phonePic}/>
        <div className={styles.smt}>
          <div className={styles.logIn}>
            <Image src={'/images/wordmark-logo.png'} alt="instagram wordmark logo" width={175} height={63}/>
            <Form/>
          </div>
          <div className={styles.signUp}>
            Don't have an account?
            <Button title="Sign Up"/>
          </div>
          <div className={styles.getApp}>
            Get the app.
            <div className={styles.getAppButtons}>
              <button>
                  <Image src={'/images/appleicon.png'} alt="apple icon logo" width={27} height={27}/>
                  <p id={styles.smalltextOne}>Dowload on the <span id={styles.largetextOne}>Apple Store</span></p>
              </button>
              <button>
                  <Image src={'/images/googleplayicon.png'} alt="google play icon logo" width={37} height={42}/>
                  <p id={styles.smalltextTwo}>GET IT ON <span id={styles.largetextTwo}>Google Play</span></p>
              </button>
            </div>
          </div>
        </div>
      </main>
      <Footer/>
    </>
  )
}
